<?php

namespace CashflowBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Transaction
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Transaction extends EntityRepository
{
    /**
     * Save transaction object.
     *
     * @param transaction $transaction Transaction object
     */
    public function save(\CashflowBundle\Entity\Transaction $transaction)
    {
        $this->_em->persist($transaction);
        $this->_em->flush();
    }

    /**
     * Delete transaction object.
     *
     * @param Transaction $transaction Transaction object
     *
     * @return mixed
     */
    public function delete(\CashflowBundle\Entity\Transaction $transaction)
    {
        if (!$transaction) {
            throw $this->createNotFoundException('No transaction found');
        }
        $this->_em->remove($transaction);
        $this->_em->flush();
    }
}
