services:
  app.wallet_repository:
    class: Doctrine\ORM\EntityRepository
    factory_service: doctrine.orm.default_entity_manager
    factory_method: getRepository
    arguments:
      - CashflowBundle\Entity\Wallet

  app.wallet_category_repository:
    class: Doctrine\ORM\EntityRepository
    factory_service: doctrine.orm.default_entity_manager
    factory_method: getRepository
    arguments:
      - CashflowBundle\Entity\WalletCategory

  app.transaction_repository:
    class: Doctrine\ORM\EntityRepository
    factory_service: doctrine.orm.default_entity_manager
    factory_method: getRepository
    arguments:
      - CashflowBundle\Entity\Transaction

  app.transaction_category_repository:
    class: Doctrine\ORM\EntityRepository
    factory_service: doctrine.orm.default_entity_manager
    factory_method: getRepository
    arguments:
      - CashflowBundle\Entity\TransactionCategory

  app.user_repository:
    class: Doctrine\ORM\EntityRepository
    factory_service: doctrine.orm.default_entity_manager
    factory_method: getRepository
    arguments:
      - CashflowBundle\Entity\User

  app.wallet_form:
    class: CashflowBundle\Form\WalletType
    tags:
      - { name: form.type, alias: wallet }

  app.wallets_controller:
    class: CashflowBundle\Controller\WalletsController
    arguments:
      - @templating
      - @app.wallet_repository
      - @form.factory
      - @security.context

  app.transactions_controller:
      class: CashflowBundle\Controller\TransactionsController
      arguments:
        - @templating
        - @app.transaction_repository
        - @app.wallet_repository
        - @form.factory

  app.static_pages_controller:
        class: CashflowBundle\Controller\StaticPagesController
        arguments:
          - @templating

