services:
  app.wallet_repository:
    class: Doctrine\ORM\EntityRepository
    factory_service: doctrine.orm.default_entity_manager
    factory_method: getRepository
    arguments:
      - CashflowBundle\Entity\Wallet

  app.wallets_controller:
    class: CashflowBundle\Controller\WalletsController
    arguments:
      - @app.wallet_repository
      - @form.factory
      - @router
      - @security.context
      - @session
      - @templating

  app.wallet_form:
      class: CashflowBundle\Form\WalletType
      tags:
        - { name: form.type, alias: wallet }

  app.wallet_category_repository:
    class: Doctrine\ORM\EntityRepository
    factory_service: doctrine.orm.default_entity_manager
    factory_method: getRepository
    arguments:
      - CashflowBundle\Entity\WalletCategory

  app.transaction_repository:
    class: Doctrine\ORM\EntityRepository
    factory_service: doctrine.orm.default_entity_manager
    factory_method: getRepository
    arguments:
      - CashflowBundle\Entity\Transaction

  app.transactions_controller:
      class: CashflowBundle\Controller\TransactionsController
      arguments:
        - @app.transaction_repository
        - @app.wallet_repository
        - @form.factory
        - @router
        - @security.context
        - @session
        - @templating

  app.transactions_form:
    class: CashflowBundle\Form\TransactionType
    tags:
      - { name: form.type, alias: transaction }
    arguments:
      - @app.wallet_repository

  app.transaction_category_repository:
    class: Doctrine\ORM\EntityRepository
    factory_service: doctrine.orm.default_entity_manager
    factory_method: getRepository
    arguments:
      - CashflowBundle\Entity\TransactionCategory

  app.user_repository:
    class: Doctrine\ORM\EntityRepository
    factory_service: doctrine.orm.default_entity_manager
    factory_method: getRepository
    arguments:
      - CashflowBundle\Entity\User

  app.static_pages_controller:
        class: CashflowBundle\Controller\StaticPagesController
        arguments:
          - @templating

