services:
#Wallet
  app.wallet_repository:
    class: Doctrine\ORM\EntityRepository
    factory_service: doctrine.orm.default_entity_manager
    factory_method: getRepository
    arguments:
      - CashflowBundle\Entity\Wallet

  app.wallets_controller:
    class: CashflowBundle\Controller\WalletsController
    arguments:
      - @app.wallet_repository
      - @form.factory
      - @router
      - @security.context
      - @session
      - @templating
      - @translator

  app.wallet_form:
      class: CashflowBundle\Form\WalletType
      tags:
        - { name: form.type, alias: wallet }
      arguments:
      - @translator

# Wallet
  app.wallet_categories_controller:
    class: CashflowBundle\Controller\WalletCategoriesController
    arguments:
      - @app.wallet_category_repository
      - @form.factory
      - @router
      - @security.context
      - @session
      - @templating
      - @translator

  app.wallet_category_repository:
    class: Doctrine\ORM\EntityRepository
    factory_service: doctrine.orm.default_entity_manager
    factory_method: getRepository
    arguments:
      - CashflowBundle\Entity\WalletCategory

#Transaction
  app.transaction_repository:
    class: Doctrine\ORM\EntityRepository
    factory_service: doctrine.orm.default_entity_manager
    factory_method: getRepository
    arguments:
      - CashflowBundle\Entity\Transaction

  app.transactions_controller:
      class: CashflowBundle\Controller\TransactionsController
      arguments:
        - @app.transaction_repository
        - @app.wallet_repository
        - @form.factory
        - @router
        - @security.context
        - @session
        - @templating
        - @translator

  app.transactions_form:
    class: CashflowBundle\Form\TransactionType
    tags:
      - { name: form.type, alias: transaction }
    arguments:
      - @app.wallet_repository
      - @translator

#Transaction Category
  app.transaction_categories_controller:
    class: CashflowBundle\Controller\TransactionCategoriesController
    arguments:
      - @app.transaction_category_repository
      - @form.factory
      - @router
      - @security.context
      - @session
      - @templating
      - @translator

  app.transaction_category_form:
    class: CashflowBundle\Form\TransactionCategoryType
    tags:
      - { name: form.type, alias: transaction }
    arguments:
      - @app.transaction_category_repository
      - @translator

  app.transaction_category_repository:
    class: Doctrine\ORM\EntityRepository
    factory_service: doctrine.orm.default_entity_manager
    factory_method: getRepository
    arguments:
      - CashflowBundle\Entity\TransactionCategory

# User
  app.user_repository:
    class: Doctrine\ORM\EntityRepository
    factory_service: doctrine.orm.default_entity_manager
    factory_method: getRepository
    arguments:
      - CashflowBundle\Entity\User

  app.users_controller:
    class: CashflowBundle\Controller\UsersController
    arguments:
      - @templating
      - @app.usermanager_service
      - @form.factory
      - @router
      - @translator
      - @session

  app.usermanager_service:
    class: FOS\UserBundle\Doctrine\UserManager
    arguments: [@security.encoder_factory, @fos_user.util.username_canonicalizer, @fos_user.util.email_canonicalizer, @fos_user.entity_manager, CashflowBundle\Entity\User]


# Static pages
  app.static_pages_controller:
    class: CashflowBundle\Controller\StaticPagesController
    arguments:
      - @templating
      - @translator
      - @app.wallet_repository
      - @security.context
      - @app.transaction_repository

