services:
  app.wallet_repository:
    class: Doctrine\ORM\EntityRepository
    factory_service: doctrine.orm.default_entity_manager
    factory_method: getRepository
    arguments:
      - CashflowBundle\Entity\Wallet

  app.transaction_repository:
    class: Doctrine\ORM\EntityRepository
    factory_service: doctrine.orm.default_entity_manager
    factory_method: getRepository
    arguments:
      - CashflowBundle\Entity\Transaction

  app.wallet_form:
    class: CashflowBundle\Form\WalletType
    tags:
      - { name: form.type, alias: wallet }

  app.wallets_controller:
    class: CashflowBundle\Controller\WalletsController
    arguments:
      - @templating
      - @app.wallet_repository
      - @form.factory
